### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Penguinehis** [0verp0wer/BlankOBFv2-deobfuscator#1]
insert the file path:Adder.py
Traceback (most recent call last):
  File "/root/decode/deobfuscator.py", line 8, in detect_layer
    content = first_layer.deobfuscate_first_layer(content)
  File "/root/decode/deobfuscator.py", line 57, in deobfuscate_first_layer
    base64_values = first_layer.get_variables_name_and_values(content)
  File "/root/decode/deobfuscator.py", line 45, in get_variables_name_and_values
    base64_values.append(eval(value))
  File "<string>", line 1
    ')), "<string>", "exec"))
    ^
SyntaxError: unterminated string literal (detected at line 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/decode/deobfuscator.py", line 17, in detect_layer
    content = second_layer.deobfuscate_second_layer(content)
  File "/root/decode/deobfuscator.py", line 95, in deobfuscate_second_layer
    name_encrypted, value = second_layer.get_variable_name_and_value(content)
  File "/root/decode/deobfuscator.py", line 67, in get_variable_name_and_value
    value = eval(match.group(2))
  File "<string>", line 1
    ')), "<string>", "exec"))
    ^
SyntaxError: unterminated string literal (detected at line 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/decode/deobfuscator.py", line 136, in <module>
    main()
  File "/root/decode/deobfuscator.py", line 133, in main
    detector.detect_layer(content)
  File "/root/decode/deobfuscator.py", line 25, in detect_layer
    content = third_layer.deobfuscate_third_layer(content)
  File "/root/decode/deobfuscator.py", line 121, in deobfuscate_third_layer
    ip_table = third_layer.get_ip_table(content)
  File "/root/decode/deobfuscator.py", line 108, in get_ip_table
    ip_table = eval(match.group(2))
  File "<string>", line 1
    ')), "<string>", "exec"))
    ^
SyntaxError: unterminated string literal (detected at line 1)

First layer

________ = [_________[5:].strip() for _________ in _____________ if _________.startswith("#____")]
if len(________) < 30 or any([len(x) != 6 for x in ________]):
    __import__("os")._exit(0)
for __________ in ________:
    _____________ = list(____________)
    ___________ = __________
    for _________, __________ in enumerate(____________):
        _____________[_________] = __________ ^ ___________.encode()[_________ % len(___________)]
    try:
        __import__(__import__("base64").b64decode(bytes([89, 110, 86, 112, 98, 72, 82, 112, 98, 110, 77, 61])).decode()).exec(__import__(__import__("base64").b64decode(bytes([101, 109, 120, 112, 89, 103, 61, 61])).decode()).decompress(bytes(_____________)))
        __import__(__import__("base64").b64decode(bytes([98, 51, 77, 61])).decode())._exit(0)
    except __import__(__import__("base64").b64decode(bytes([101, 109, 120, 112, 89, 103, 61, 61])).decode()).error:
        pass
        
        second layer
        
        __import__(__import__("base64").b64decode(bytes([89, 110, 86, 112, 98, 72, 82, 112, 98, 110, 77, 61])).decode()).exec(__import__(__import__("base64").b64decode(bytes([98, 87, 70, 121, 99, 50, 104, 104, 98, 65, 61, 61])).decode()).loads(__import__(__import__("base64").b64decode(bytes([89, 109, 70, 122, 90, 84, 89, 48])).decode()).b64decode(__import__(__import__("base64").b64decode(bytes([89, 50, 57, 107, 90, 87, 78, 122])).decode()).decode(____, __import__(__import__("base64").b64decode(bytes([89, 109, 70, 122, 90, 84, 89, 48])).decode()).b64decode("cm90MTM=").decode())+_____+______[::-1]+_______)))

**Comment by 0verp0wer** [comment]
> insert the file path:Adder.py Traceback (most recent call last): File "/root/decode/deobfuscator.py", line 8, in detect_layer content = first_layer.deobfuscate_first_layer(content) File "/root/decode/deobfuscator.py", line 57, in deobfuscate_first_layer base64_values = first_layer.get_variables_name_and_values(content) File "/root/decode/deobfuscator.py", line 45, in get_variables_name_and_values base64_values.append(eval(value)) File "", line 1 ')), "", "exec")) ^ SyntaxError: unterminated string literal (detected at line 1)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/root/decode/deobfuscator.py", line 17, in detect_layer content = second_layer.deobfuscate_second_layer(content) File "/root/decode/deobfuscator.py", line 95, in deobfuscate_second_layer name_encrypted, value = second_layer.get_variable_name_and_value(content) File "/root/decode/deobfuscator.py", line 67, in get_variable_name_and_value value = eval(match.group(2)) File "", line 1 ')), "", "exec")) ^ SyntaxError: unterminated string literal (detected at line 1)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/root/decode/deobfuscator.py", line 136, in main() File "/root/decode/deobfuscator.py", line 133, in main detector.detect_layer(content) File "/root/decode/deobfuscator.py", line 25, in detect_layer content = third_layer.deobfuscate_third_layer(content) File "/root/decode/deobfuscator.py", line 121, in deobfuscate_third_layer ip_table = third_layer.get_ip_table(content) File "/root/decode/deobfuscator.py", line 108, in get_ip_table ip_table = eval(match.group(2)) File "", line 1 ')), "", "exec")) ^ SyntaxError: unterminated string literal (detected at line 1)
> 
> First layer
> 
> ________ = [**_**[5:].strip() for _________ in _____________ if _**.startswith("#")] if len(**_**_) < 30 or any([len(x) != 6 for x in _**_**]): import("os")._exit(0) for __________ in **: _____________ = list(**_**_) ___________ = __________ for _**, __________ in enumerate(**_**_): _____**[**_] = __________ ^ _**.encode()[**_ % len(**_)] try: **import**(**import**("base64").b64decode(bytes([89, 110, 86, 112, 98, 72, 82, 112, 98, 110, 77, 61])).decode()).exec(**import**(**import**("base64").b64decode(bytes([101, 109, 120, 112, 89, 103, 61, 61])).decode()).decompress(bytes(_____________))) **import**(**import**("base64").b64decode(bytes([98, 51, 77, 61])).decode())._exit(0) except **import**(**import**("base64").b64decode(bytes([101, 109, 120, 112, 89, 103, 61, 61])).decode()).error: pass
> 
> ```
>     second layer
>     
>     __import__(__import__("base64").b64decode(bytes([89, 110, 86, 112, 98, 72, 82, 112, 98, 110, 77, 61])).decode()).exec(__import__(__import__("base64").b64decode(bytes([98, 87, 70, 121, 99, 50, 104, 104, 98, 65, 61, 61])).decode()).loads(__import__(__import__("base64").b64decode(bytes([89, 109, 70, 122, 90, 84, 89, 48])).decode()).b64decode(__import__(__import__("base64").b64decode(bytes([89, 50, 57, 107, 90, 87, 78, 122])).decode()).decode(____, __import__(__import__("base64").b64decode(bytes([89, 109, 70, 122, 90, 84, 89, 48])).decode()).b64decode("cm90MTM=").decode())+_____+______[::-1]+_______)))
> ```

Hi, please upload the file here or send it on my discord
discord: over_on_top

**Comment by Penguinehis** [comment]
> > insert the file path:Adder.py Traceback (most recent call last): File "/root/decode/deobfuscator.py", line 8, in detect_layer content = first_layer.deobfuscate_first_layer(content) File "/root/decode/deobfuscator.py", line 57, in deobfuscate_first_layer base64_values = first_layer.get_variables_name_and_values(content) File "/root/decode/deobfuscator.py", line 45, in get_variables_name_and_values base64_values.append(eval(value)) File "", line 1 ')), "", "exec")) ^ SyntaxError: unterminated string literal (detected at line 1)
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last): File "/root/decode/deobfuscator.py", line 17, in detect_layer content = second_layer.deobfuscate_second_layer(content) File "/root/decode/deobfuscator.py", line 95, in deobfuscate_second_layer name_encrypted, value = second_layer.get_variable_name_and_value(content) File "/root/decode/deobfuscator.py", line 67, in get_variable_name_and_value value = eval(match.group(2)) File "", line 1 ')), "", "exec")) ^ SyntaxError: unterminated string literal (detected at line 1)
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last): File "/root/decode/deobfuscator.py", line 136, in main() File "/root/decode/deobfuscator.py", line 133, in main detector.detect_layer(content) File "/root/decode/deobfuscator.py", line 25, in detect_layer content = third_layer.deobfuscate_third_layer(content) File "/root/decode/deobfuscator.py", line 121, in deobfuscate_third_layer ip_table = third_layer.get_ip_table(content) File "/root/decode/deobfuscator.py", line 108, in get_ip_table ip_table = eval(match.group(2)) File "", line 1 ')), "", "exec")) ^ SyntaxError: unterminated string literal (detected at line 1)
> > First layer
> > ________ = [**_**[5:].strip() for _________ in _____________ if _**.startswith("#")] if len(**_**_) < 30 or any([len(x) != 6 for x in _**_**]): import("os")._exit(0) for __________ in **: _____________ = list(**_**_) ___________ = __________ for _**, __________ in enumerate(**_**_): _____**[**_] = __________ ^ _**.encode()[**_ % len(**_)] try: **import**(**import**("base64").b64decode(bytes([89, 110, 86, 112, 98, 72, 82, 112, 98, 110, 77, 61])).decode()).exec(**import**(**import**("base64").b64decode(bytes([101, 109, 120, 112, 89, 103, 61, 61])).decode()).decompress(bytes(_____________))) **import**(**import**("base64").b64decode(bytes([98, 51, 77, 61])).decode())._exit(0) except **import**(**import**("base64").b64decode(bytes([101, 109, 120, 112, 89, 103, 61, 61])).decode()).error: pass
> > ```
> >     second layer
> >     
> >     __import__(__import__("base64").b64decode(bytes([89, 110, 86, 112, 98, 72, 82, 112, 98, 110, 77, 61])).decode()).exec(__import__(__import__("base64").b64decode(bytes([98, 87, 70, 121, 99, 50, 104, 104, 98, 65, 61, 61])).decode()).loads(__import__(__import__("base64").b64decode(bytes([89, 109, 70, 122, 90, 84, 89, 48])).decode()).b64decode(__import__(__import__("base64").b64decode(bytes([89, 50, 57, 107, 90, 87, 78, 122])).decode()).decode(____, __import__(__import__("base64").b64decode(bytes([89, 109, 70, 122, 90, 84, 89, 48])).decode()).b64decode("cm90MTM=").decode())+_____+______[::-1]+_______)))
> > ```
> 
> Hi, please upload the file here or send it on my discord discord: over_on_top


sended to you the friend request my name is Recon Cuddly, penguinehis
